package com.company.EXCEPTION_HANDLING;

/*
Try with resources can be used with catch block
Any thing that is within try with sources must implement AutoClosable Interface
it automatically closes connection after use.

 */
public class TryWithResources {
    public static void main(String[] args) {
  /*      try(

                //write some connection opening  code here
                ) {

        }
        try (){

        } catch (Exception e){

        }*/
    }
}
